Controllers/AdminController.cs
using iBookStore.Models;
using iBookStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace iBookStore.Controllers
{

        public class AdminController : Controller
        {
            private readonly RoleManager<IdentityRole> _roleManager;
            private readonly UserManager<DefaultUser> _userManager;

            public AdminController(RoleManager<IdentityRole> roleManager, UserManager<DefaultUser> userManager)
            {
                _roleManager = roleManager;
                _userManager = userManager;
            }

            [HttpGet]
            public IActionResult ListAllRoles()
            {
                var roles = _roleManager.Roles;
                return View(roles);
            }

            [HttpGet]
            public IActionResult AddRole()
            {
                return View();
            }

            [HttpPost]
            public async Task<IActionResult> AddRole(AddRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new()
                {
                    Name = model.RoleName
                };

                var result = await _roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListAllRoles");

                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            

            return View(model);
            }

            [HttpGet]
            public async Task<IActionResult> EditRole(string id)
            {
                var role = await _roleManager.FindByIdAsync(id);

                if (role == null)
                {
                    ViewData["ErrorMessage"] = $"No role with Id '{id}' was found";
                    return View("Error");
                }

                EditRoleViewModel model = new()
                {
                    Id = role.Id,
                    RoleName = role.Name
                };

                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        model.Users.Add(user.UserName);
                    }
                }

                return View(model);
            }

            [HttpPost]
            public async Task<IActionResult> EditRole(EditRoleViewModel model)
            {
                var role = await _roleManager.FindByIdAsync(model.Id);

                if (role == null)
                {
                    ViewData["ErrorMessage"] = $"No role with Id '{model.Id}' was found";
                    return View("Error");
                }
                else
                {
                    role.Name = model.RoleName;

                    var result = await _roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListAllRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                    return View(model);
                }
            }

            [HttpGet]
            public async Task<IActionResult> EditUsersInRole(string id)
            {
                var role = await _roleManager.FindByIdAsync(id);

                ViewData["roleId"] = id;
                ViewData["roleName"] = role.Name;

                if (role == null)
                {
                    ViewData["ErrorMessage"] = $"No role with Id '{id}' was found";
                    return View("Error");
                }

                var model = new List<UserRoleViewModel>();

                foreach (var user in _userManager.Users)
                {
                    UserRoleViewModel userRoleVM = new()
                    {
                        Id = user.Id,
                        Name = user.UserName
                    };

                    if (await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        userRoleVM.IsSelected = true;
                    }
                    else
                    {
                        userRoleVM.IsSelected = false;
                    }

                    model.Add(userRoleVM);
                }

                return View(model);
            }

            [HttpPost]
            public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string id)
            {
                var role = await _roleManager.FindByIdAsync(id);

                if (role == null)
                {
                    ViewData["ErrorMessage"] = $"No role with Id '{id}' was found";
                    return View("Error");
                }

                for (int i = 0; i < model.Count; i++)
                {
                    var user = await _userManager.FindByIdAsync(model[i].Id);

                    if (model[i].IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                    {
                        await _userManager.AddToRoleAsync(user, role.Name);
                    }
                    else if (!model[i].IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        await _userManager.RemoveFromRoleAsync(user, role.Name);
                    }
                    else
                    {
                        continue;
                    }
                }

                return RedirectToAction("EditRole", new { Id = id });
            }

            [HttpGet]
            public async Task<IActionResult> DeleteRole(string id)
            {
                var role = await _roleManager.FindByIdAsync(id);

                return View(role);
            }

            [HttpPost]
            public async Task<IActionResult> ConfirmDelete(string id)
            {
                var role = await _roleManager.FindByIdAsync(id);

                if (role == null)
                {
                    ViewData["ErrorMessage"] = $"No role with Id '{id}' was found";
                    return View("Error");
                }
                else
                {
                    var result = await _roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                    return RedirectToAction("ListAllRoles");

                }

                foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                
                return View(role);
                }
            }
        }
    }

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using iBookStore.Data;
using iBookStore.Models;

namespace iBookStore.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
              return _context.Books != null ? 
                          View(await _context.Books.ToListAsync()) :
                          Problem("Entity set 'iBookStoreContext.Book'  is null.");
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Language,ISBN,DatePublished,Price,Author,ImageUrl")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                TempData["success"] = "Book was added successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Language,ISBN,DatePublished,Price,Author,ImageUrl")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Books == null)
            {
                return Problem("Entity set 'iBookStoreContext.Book'  is null.");
            }
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            TempData["success"] = "Book was deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
          return (_context.Books?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/StoreController.cs
using iBookStore.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace iBookStore.Controllers { 
    [AllowAnonymous]
public class StoreController : Controller
{
    private readonly ApplicationDbContext _context;

    public StoreController(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(string searchString, string minPrice, string maxPrice)
    {
        var books = _context.Books.Select(b => b);

        if (!string.IsNullOrEmpty(searchString))
        {
            books = books.Where(b => b.Title.Contains(searchString) || b.Author.Contains(searchString));
        }

        if (!string.IsNullOrEmpty(minPrice))
        {
            var min = int.Parse(minPrice);
            books = books.Where(b => b.Price >= min);
        }

        if (!string.IsNullOrEmpty(maxPrice))
        {
            var max = int.Parse(maxPrice);
            books = books.Where(b => b.Price <= max);
        }

        return View(await books.ToListAsync());
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var book = await _context.Books
            .FirstOrDefaultAsync(m => m.Id == id);
        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }
}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iBookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/myCustomCss.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <style>
        /* Custom Styles */
        body {
            font-family: Arial, sans-serif;
            background-color: #fff2e6;
        }


        .navbar {     
            padding-bottom: 10px;
            margin-top: 30px;
            background-color: #d14d4d;
            
        }

        .container{
            padding-top: 10px;
        }

        .navbar-brand {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }

        .navbar-toggler-icon {
            background-color: #333;
        }

        .navbar-nav .nav-item .nav-link {
            color: #000000;
            transition: color 0.3s;
        }

            .navbar-nav .nav-item .nav-link:hover {
                color: #007bff;
            }

   

        .box-shadow {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .pb-3 {
            padding-bottom: 20px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">iBookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Store" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Books" asp-action="Index">Book List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ListAllRoles">Roles</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}


@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}